name: Auto build all files with python script,111

on:
  push:
    branches: 
      - main

permissions: write-all

jobs:
  auto-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Python script
        run: |
          python auto.py
      
      - name: Update README
        run: |
          if git diff --quiet; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "docs(action): Update README.md"
            git push https://Kenny-Huang-mz@github.com/Kenny-Huang-mz/slides.git HEAD:main
            exit 0
          fi

      - name: Move files
        run: |
          mv ./dist ./slides
          mv ./slides/index.html ./index.html

      - name: Push Page branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "feat(action): Generate page"
          git pull
          git push --force https://Kenny-Huang-mz@github.com/Kenny-Huang-mz/slides.git HEAD:vercel
      
      - name: Move files
        run: |
          mv ./slides/* ./

      - name: Push Page branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "feat(action): Generate page"
          git pull
          git push --force https://Kenny-Huang-mz@github.com/Kenny-Huang-mz/slides.git HEAD:pages
      